import Head from "next/head";
import { Layout } from "@/components/Layout";
import { useRouter } from "next/router";
import { CargoContent } from "@/components/CargoContent";
import Search from "@/components/Layout/Search";
import { getShipsList } from "@/api/ships";

export default function Ship(props) {
  const router = useRouter();
  let ship;

  if (router.query.keyword && router.query.keyword !== "")
    ship = props.ships.filter((ship) => ship.name === router.query.keyword)[0];
  else ship = props.ship[0];

  return (
    <>
      <Head>
        <title>SpaceX Cargo Planner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout data={props.ships}>
        <div className="hidden md:block">
          <Search />
        </div>
        <div className="bg-gradient w-full h-full px-[50px] pt-[30px] md:px-[15px]">
          {ship ? (
            <CargoContent ship={ship} />
          ) : (
            <h1 className="text-white text-[64px] md:text-[28px]">{`${router.query.keyword} doesnt found`}</h1>
          )}
        </div>
      </Layout>
    </>
  );
}

export async function getServerSideProps({ params }) {
  try {
    const ships = await getShipsList();
    const ship = ships.filter((ship) => ship.id === params.id);

    return {
      props: {
        ships,
        ship,
      },
    };
  } catch (e) {
    return {
      props: {
        ships: [],
        ship: [],
      },
    };
  }
}
