import React from "react";
import Head from "next/head";
import { Layout } from "@/components/Layout";
import { getShipsList } from "@/api/ships";
import { useRouter } from "next/router";

export default function Ships(props) {
  const router = useRouter();

  React.useEffect(() => {
    if (router.query.keyword)
      router.push(
        `/ships/${
          props.ships.filter((ship) => ship.name === router.query.keyword)[0].id
        }`
      );
  }, [router, props.ships]);

  return (
    <>
      <Head>
        <title>SpaceX Cargo Planner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout data={props.ships} />
    </>
  );
}

export async function getServerSideProps() {
  try {
    const ships = await getShipsList();

    return {
      props: {
        ships,
      },
    };
  } catch (e) {
    return {
      props: {
        ships: [],
      },
    };
  }
}
